apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
spec:
  replicas: {{ .Values.container.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.appName }}
  template:
    metadata:
      labels:
        component: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.container.port }}