apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ lower .Values.service.type }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    component: {{ .Values.appName }}